language: node_js
node_js: lts/*
sudo: false
install:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  project: "shopping-cart"
  token:
    - 1/RGJVLPZVBeGUh_jGV9my0t0O4jgUyOUUEaC6pWKsXtQNipKZZKwj6DdY8ZZzFhpV
script: echo "script"
